apiVersion: v1
kind: ConfigMap
metadata:
  name: database-cm
  namespace: ams-backend
data:
  provider_database_url: jdbc:mysql://mysql-svc.ams-database.svc.cluster.local:3306/provider_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
  article_database_url: jdbc:mysql://mysql-svc.ams-database.svc.cluster.local:3306/article_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
