---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: provider-sts
  namespace: ams-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider
  serviceName: provider
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: database-username
              name: backend-secrets
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: backend-secrets
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              key: provider_database_url
              name: database-cm
        - name: EUREKA_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              key: eureka_service_address
              name: eureka-cm
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        image: sipacademy2024/serviceprovider
        imagePullPolicy: IfNotPresent
        name: provider
        ports:
        - containerPort: 8001
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: provider-svc
  namespace: ams-backend
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: provider
---
apiVersion: v1
kind: Service
metadata:
  name: provider-svc
  namespace: ams-backend
spec:
  ports:
  - nodePort: 30100
    port: 80
    targetPort: 8080
  selector:
    app: provider
  type: NodePort
