apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: provider-sts
  namespace: ams-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider
  serviceName: provider
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
      - name: provider
        image: ziedab/amsms-provider-svc
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
          name: http
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: database-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: database-password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: database-cm
              key: provider_database_url
        - name: EUREKA_INSTANCE_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: eureka-cm
              key: eureka_service_hostname
---
apiVersion: v1
kind: Service
metadata:
  name: provider-svc
  namespace: ams-backend
spec:
  selector:
    app: provider
  ports:
  - port: 80
    targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: provider-nodeport-svc
  namespace: ams-backend
spec:
  selector:
    app: provider
  ports:
  - port: 80
    targetPort: 8001
    nodePort: 30100
  type: NodePort
