apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: provider-sts
  namespace: ams-backend
spec:
  selector:
    matchLabels:
      app: provider
  serviceName: "provider"
  replicas: 1
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
        - name: provider
          image: ziedab/amsms-provider-svc:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: database-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: database-password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: database-cm
                  key: provider_database_url
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: eureka_service_address
                  name: eureka-cm
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: provider-svc
  namespace: ams-backend
spec:
  clusterIP: None
  selector:
    app: provider
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: provider-svc
  namespace: ams-backend
spec:
  type: NodePort
  selector:
    app: provider
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30100  # Choose an available nodePort value, or let Kubernetes assign one automatically

      
