---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: proxy-sts
  namespace: ams-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  serviceName: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - env:
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: eureka_service_address
              name: eureka-cm
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        image: ziedab/amsms-gateway-svc:1.0.0
        imagePullPolicy: IfNotPresent
        name: proxy
        ports:
        - containerPort: 9092
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: ams-backend
spec:
  ports:
  - name: proxy
    nodePort: 30150
    port: 80
    targetPort: 8080
  selector:
    app: proxy
  type: NodePort
