apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: proxy-sts
  namespace: ams-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  serviceName: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: ziedab/sip-serviceproxy
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s" 
        ports:
        - containerPort: 9092
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: ams-backend
spec:
  ports:
  - name: proxy
    nodePort: 30150
    port: 80
    targetPort: 9092  # Corrected targetPort to match the container port
  selector:
    app: proxy
  type: NodePort
