apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  namespace: ams-backend
spec:
  serviceName: "eureka"
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: bitinit/eureka
        imagePullPolicy: Always
        ports:
        - containerPort: 8761
        env:
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: eureka-cm
              key: eureka_service_address

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-nodeport
  namespace: ams-backend
  labels:
    app: eureka
spec:
  ports:
  - nodePort: 31300
    port: 8761
  selector:
    app: eureka
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: ams-backend
  labels:
    app: eureka
spec:
  clusterIP: None
  ports:
  - port: 8761
    name: eureka
  selector:
    app: eureka
