# eureka
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  namespace: ams-backend
spec:
  serviceName: "eureka"
  # n instances
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: ziedab/amsms-eureka-svc:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8761
        env:
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: eureka-cm
              key: eureka_service_address        
        #          env:
        #            - name: EUREKA_INSTANCE_PREFERIPADDRESS
        #              value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: ams-backend
  labels:
    app: eureka
spec:
  ports:
  - nodePort: 31300
    port: 8761
  selector:
    app: eureka
  type: NodePort
