---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  namespace: ams-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  serviceName: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        image: ziedab/amsms-eureka-svc:1.0.0
        imagePullPolicy: Always
        name: eureka
        ports:
        - containerPort: 8761      
      - env:
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: eureka_service_address
              name: eureka-cm
              
---
# Comment out the following service to disable NodePort 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eureka
  name: eureka
  namespace: ams-backend
spec:
  ports:
  - nodePort: 31300
    port: 8761
  selector:
    app: eureka
  type: NodePort

# Uncomment the following service to use ClusterIP
#apiVersion: v1
#kind: Service
#metadata:
#  name: eureka
#  namespace: ams-backend
#  labels:
#    app: eureka
#spec:
#  clusterIP: None
#  ports:
#  - port: 8761
#    name: eureka
#  selector:
#    app: eureka
