version: '3.7'  
services:

  eureka:
    image: ziedab/amsms-eureka-svc
    ports:
      - '8761:8761'
    container_name: service_eureka_cont
    restart: always
    networks:
      - amsmicroservicesapp

  provider:
    image: ziedab/sip-serviceprovider
    ports:
      - '8001:8001'
    container_name: service_provider_cont
    depends_on:
      eureka:
        condition: service_started
      dbprovider:
        condition: service_healthy
        restart: true      
    environment:
      SPRING_PROFILES_ACTIVE: docker 
      SPRING_DATASOURCE_URL: jdbc:mysql://dbprovider:3306/service_provider?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: provider
      SPRING_DATASOURCE_PASSWORD: providerf7er7
    networks:
      - amsmicroservicesapp

  dbprovider:
    image: 'mysql:latest'
    container_name: service_db_provider_cont
    volumes:
      - 'provider_db_data:/var/lib/mysql'
    restart: always 
    environment:
      MYSQL_DATABASE: service_provider
      MYSQL_USER: provider
      MYSQL_PASSWORD: providerf7er7
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 3      
    networks:
      - amsmicroservicesapp

  article:
    image: ziedab/sip-servicearticle
    ports:
      - '8003:8003'
    container_name: service_article_cont
    depends_on:
      eureka:
        condition: service_started
      provider:
        condition: service_started
      dbarticle:
        condition: service_healthy
        restart: true 
    environment:
      SPRING_PROFILES_ACTIVE: docker 
      SPRING_DATASOURCE_URL: jdbc:mysql://dbarticle:3306/service_article?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: article
      SPRING_DATASOURCE_PASSWORD: articlec87ef8
    networks:
      - amsmicroservicesapp

  dbarticle:
    image: 'mysql:latest'
    container_name: service_db_article_cont
    volumes:
      - 'article_db_data:/var/lib/mysql'
    #restart: always
    environment:
      MYSQL_DATABASE: service_article
      MYSQL_USER: article
      MYSQL_PASSWORD: articlec87ef8
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 3      
    networks:
      - amsmicroservicesapp

  proxy:
    image: ziedab/amsms-gateway-svc
    container_name: service_proxy_cont
    ports:
      - '9092:9092'
    depends_on:
      - eureka
    restart: always
    environment:
      EUREKA_INSTANCE_HOSTNAME: eureka
    networks:
      - amsmicroservicesapp

  phpmyadmin:
    image: phpmyadmin
    container_name: service_pmadmin_cont
    restart: always
    depends_on:
      - dbprovider
      - dbarticle
    ports:
      - '8077:80'
    environment:
      - PMA_ARBITRARY=1
    networks:
      - amsmicroservicesapp
volumes:
  provider_db_data:
  article_db_data:
networks:
  amsmicroservicesapp:
